version: "3.0"
services:
  server:
    build: .
    command: >
      sh -c "npm install && npm start"
    container_name: interface-globo-card
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always 
    tty: true
    stdin_open: true   
    volumes:
      - ./:/home/node/app
