const cardType = {
  CARD_CREATE: 'CARD_CREATE',
  CARD_DELETE: 'CARD_DELETE',
  CARD_ALL: 'CARD_ALL',
  CARD_SELECT: 'CARD_SELECT',
  CARD_SEARCH: 'CARD_SEARCH',
  CARD_EDIT: 'CARD_EDIT',
  CARD_ERROR: 'CARD_ERROR',
  CARD_SUCCESS: 'CARD_SUCCESS',
  CARD_CLEAR_ERROR: 'CARD_CLEAR_ERROR',
  CARD_LOADING: 'CARD_LOADING'
}

export {
  cardType
}
